// Assets to be created and funded to the Liquidity Pool
// (Name, decimals, quantity, URI)
export const ASSETS: [string, string, string, string, number, number][] = [
    [
        'Cannon',
        'CAN',
        'A cannon for defending yer ship!',
        'https://arweave.net/ArreGQ6DYdIPGs_KiwVXE7AMVclLliICTlls6Ff8DbY',
        3,
        80,
    ],
    [
        'Cannon Ball',
        'CANB',
        'Cannon balls for yer cannons!',
        'https://arweave.net/ZlxqEw-BVEO7LKLWE7uKJoCxC67w-0zaO9ydX-m6y7A',
        9,
        60,
    ],
    [
        'Compass',
        'COMP',
        'A compass to navigate the seven seas!',
        'https://arweave.net/MvWxgCu231-0IrE3FWoaAYoFaD1MgWKOqDjCv5v6LEA',
        3,
        20,
    ],
    [
        'Fishing Net',
        'FISH',
        'A fishing net for catching meals for the crew!',
        'https://arweave.net/2wCk8mVH8KyqwbYLlxae9kBBKb4jTRPeiXVrqUTvjUE',
        3,
        50,
    ],
    [
        'Gold',
        'GOLD',
        'Ahh the finest gold in all of these waters!',
        'https://arweave.net/46B9y63MXlLnprZLvrRjS_50yecOydiLbxTbieAREBk',
        6,
        500,
    ],
    [
        'Grappling Hook',
        'GRAP',
        'A grappling hook for boarding other ships!',
        'https://arweave.net/RT9sF6ENI__DQGYD74H4SdncsjLyeO1Rm3dRQ1T1Tz0',
        3,
        50,
    ],
    [
        'Gunpowder',
        'GUNP',
        'Gunpowder for ye muskets!',
        'https://arweave.net/eLqSxbbW7ATsQioluBZt9KG0YnU0jRoR_46g0EJU75Q',
        9,
        60,
    ],
    [
        'Musket',
        'MUSK',
        'A musket for firing on enemies!',
        'https://arweave.net/tKdMfImOkHEqo8xWulIv92MybdpkbnWjDJmazj3lTpU',
        3,
        60,
    ],
    [
        'Rum',
        'RUM',
        'Rum, more rum!',
        'https://arweave.net/NJGvUP2EuK-LJ7QV6qRifcGC8ao2Vd9WSW2GjiGSpVw',
        6,
        100,
    ],
    [
        'Telescope',
        'TELE',
        'A telescope for spotting booty amongst the seas!',
        'https://arweave.net/NmBFKuCWk4yfAB4a6EGwXlWM92q5B9nBZMlRhpVA4y4',
        3,
        20,
    ],
    [
        'Treasure Map',
        'TMAP',
        'A map to help ye find long lost treasures!',
        'https://arweave.net/_cM90jcVdRRYt-OA8xIV--gZCAOpe18BCLvV2TVW7Fc',
        3,
        10,
    ],
]
